################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 1.7
##  \   \         Application : Virtex-5 FPGA GTX Transceiver Wizard
##  /   /         Filename : implement_sh.ejava 
## /___/   /\     Timestamp :
## \   \  /  \
##  \___\/\___\
##
##
## implement.sh script 
## Generated by Xilinx GTX Transceiver Wizard
##

#!/bin/bash
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the wizard
#-----------------------------------------------------------------------------

##---------------------Change CWD to results-------------------------------------

#Clean results directory
#Create results directory
#Change current directory to results
echo "WARNING: Removing existing results directory"
rm -rf results
mkdir results
cp xst.prj      ./results
cp xst.scr      ./results
cp *.ngc        ./results

##-----------------------------Run Synthesis-------------------------------------

echo "### Running Xst - "
xst -ifn xst.scr

cp gtxf_top.ngc ./results
cd ./results

##-------------------------------Run ngdbuild---------------------------------------

echo 'Running ngdbuild'
ngdbuild -uc ../../example_design/gtxf_top.ucf -p xc5vfx70t-ff1136-1 gtxf_top.ngc gtxf_top.ngd

#end run ngdbuild section

##-------------------------------Run map-------------------------------------------

echo 'Running map'
map -p xc5vfx70t-ff1136-1 -o mapped.ncd gtxf_top.ngd

##-------------------------------Run par-------------------------------------------

echo 'Running par'
par mapped.ncd routed.ncd

##---------------------------Report par results-------------------------------------

echo 'Running design through bitgen'
bitgen -w routed

##-------------------------------Trace Report---------------------------------------

echo 'Running trce'
trce -e 10 routed.ncd mapped.pcf -o routed 

##-------------------------------Run netgen------------------------------------------

echo 'Running netgen to create gate level Verilog model'
netgen -ofmt verilog -sim -dir . -tm gtxf_top -w routed.ncd routed.v

#Change directory to implement

cd ..

