REM   ____  ____
REM  /   /\/   /
REM /___/  \  /
REM \   \   \/     Vendor: Xilinx
REM  \   \         Version : 1.7
REM  /   /         Application : GTX Transceiver Wizard
REM /___/   /\     Filename : simulate_isim.bat
REM \   \  /  \
REM  \___\/\___\
REM
REM
REM Script SIMULATE_ISIM.BAT
REM Generated by Xilinx GTX Transceiver Wizard


REM ***************************** Beginning of Script ***************************
        

REM Create and map work directory
mkdir work


REM MGT Wrapper
vlogcomp -work work  ..\..\..\gtxf_tile.v
vlogcomp -work work  ..\..\..\gtxf.v


vlogcomp -work work  ..\..\example_design\mgt_usrclk_source_pll.v


REM Example Design modules
vlogcomp -work work  ..\..\example_design\frame_gen.v
vlogcomp -work work  ..\..\example_design\frame_check.v
vlogcomp -work work  ..\..\example_design\gtxf_top.v
vlogcomp -work work  ..\demo_tb.v

REM Other modules
vlogcomp -work work %XILINX%\verilog\src\glbl.v

REM Load Design
fuse work.DEMO_TB work.glbl -L unisims_ver -L secureip -o demo_tb.exe

.\demo_tb.exe gui -tclbatch wave_isim.tcl -wdb wave_isim  


