   
################################################################################
##$Date: 2009/11/24 11:45:46 $
##$Revision: 1.2 $
################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /
## \   \   \/     Vendor: Xilinx
##  \   \         Version : 1.7
##  /   /         Application : GTX Transceiver Wizard
## /___/   /\     Filename : simulate_mti.do
## \   \  /  \
##  \___\/\___\
##
##
## Script SIMULATE_MTI.DO
## Generated by Xilinx GTX Transceiver Wizard


##***************************** Beginning of Script ***************************
        
## If MTI_LIBS is defined, map unisim and simprim directories using MTI_LIBS
## This mode of mapping the unisims libraries is provided for backward 
## compatibility with previous wizard releases. If you don't set MTI_LIBS
## the unisim libraries will be loaded from the paths set up by compxlib in
## your modelsim.ini file

set XILINX   $env(XILINX)
if [info exists env(MTI_LIBS)] {    
    set MTI_LIBS $env(MTI_LIBS)
    vlib UNISIMS_VER
    vmap UNISIMS_VER $MTI_LIBS/unisims_ver
   
    vlib SECUREIP
    vmap SECUREIP $MTI_LIBS/secureip
}

## Create and map work directory
vlib work
vmap work work



##MGT Wrapper
vlog -work work  ../../../gtxf_tile.v;
vlog -work work  ../../../gtxf.v;


vlog -work work  ../../example_design/mgt_usrclk_source_pll.v;


##Example Design modules
vlog -work work  ../../example_design/frame_gen.v;
vlog -work work  ../../example_design/frame_check.v;
vlog -work work  ../../example_design/gtxf_top.v;
vlog -work work  ../demo_tb.v;

##Other modules
vlog -work work $XILINX/verilog/src/glbl.v;

##Load Design
vsim -t 100fs -L SECUREIP -L UNISIMS_VER work.DEMO_TB work.glbl -voptargs="+acc"

##Load signals in wave window
view wave
do wave_mti.do

##Run simulation
run 50 us



