   
################################################################################
##$Date: 2010/02/16 10:19:59 $
##$Revision: 1.6 $
################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /
## \   \   \/     Vendor: Xilinx
##  \   \         Version : 1.7
##  /   /         Application : GTX Transceiver Wizard
## /___/   /\     Filename : simulate_isim.sh
## \   \  /  \
##  \___\/\___\
##
##
## Script SIMULATE_ISIM.SH
## Generated by Xilinx GTX Transceiver Wizard


##***************************** Beginning of Script ***************************
        

## Create and map work directory
mkdir work


##MGT Wrapper
vlogcomp -work work  ../../../gtxf_tile.v;
vlogcomp -work work  ../../../gtxf.v;


vlogcomp -work work  ../../example_design/mgt_usrclk_source_pll.v;


##Example Design modules
vlogcomp -work work  ../../example_design/frame_gen.v;
vlogcomp -work work  ../../example_design/frame_check.v;
vlogcomp -work work  ../../example_design/gtxf_top.v;
vlogcomp -work work  ../demo_tb.v;

##Other modules
vlogcomp -work work $XILINX/verilog/src/glbl.v;

##Load Design
fuse work.DEMO_TB work.glbl -L unisims_ver -L secureip -o demo_tb.exe

./demo_tb.exe -gui -tclbatch wave_isim.tcl -wdb wave_isim  


