--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.7
--  \   \         Application : xaw2vhdl
--  /   /         Filename : clock_pll.vhd
-- /___/   /\     Timestamp : 05/18/2015 17:00:06
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st /home/pirovaldes/Data/Documents/Documents/apps/ml507/ipcore_dir/clock_pll.xaw /home/pirovaldes/Data/Documents/Documents/apps/ml507/ipcore_dir/clock_pll
--Design Name: clock_pll
--Device: xc5vfx70t-1ff1136
--
-- Module clock_pll
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT0 = 0.191 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT1 = 0.167 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT2 = 0.146 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity clock_pll is
   port ( CLKIN_IN        : in    std_logic; 
          DADDR_IN        : in    std_logic_vector (4 downto 0); 
          DCLK_IN         : in    std_logic; 
          DEN_IN          : in    std_logic; 
          DI_IN           : in    std_logic_vector (15 downto 0); 
          DWE_IN          : in    std_logic; 
          RST_IN          : in    std_logic; 
          CLKIN_IBUFG_OUT : out   std_logic; 
          CLKOUT0_OUT     : out   std_logic; 
          CLKOUT1_OUT     : out   std_logic; 
          CLKOUT2_OUT     : out   std_logic; 
          DRDY_OUT        : out   std_logic; 
          LOCKED_OUT      : out   std_logic);
end clock_pll;

architecture BEHAVIORAL of clock_pll is
   signal CLKFBOUT_CLKFBIN   : std_logic;
   signal CLKFB_IN           : std_logic;
   signal CLKIN_IBUFG        : std_logic;
   signal CLKOUT0_BUF        : std_logic;
   signal CLKOUT1_BUF        : std_logic;
   signal CLKOUT2_BUF        : std_logic;
   signal CLK0_BUF           : std_logic;
   signal DCM_LOCKED_INV_IN  : std_logic;
   signal GND_BIT            : std_logic;
   signal GND_BUS_7          : std_logic_vector (6 downto 0);
   signal GND_BUS_16         : std_logic_vector (15 downto 0);
   signal PLL_LOCKED_INV_RST : std_logic;
   signal VCC_BIT            : std_logic;
begin
   GND_BIT <= '0';
   GND_BUS_7(6 downto 0) <= "0000000";
   GND_BUS_16(15 downto 0) <= "0000000000000000";
   VCC_BIT <= '1';
   CLKIN_IBUFG_OUT <= CLKIN_IBUFG;
   CLKIN_IBUFG_INST : IBUFG
      port map (I=>CLKIN_IN,
                O=>CLKIN_IBUFG);
   
   CLKOUT0_BUFG_INST : BUFG
      port map (I=>CLKOUT0_BUF,
                O=>CLKOUT0_OUT);
   
   CLKOUT1_BUFG_INST : BUFG
      port map (I=>CLKOUT1_BUF,
                O=>CLKOUT1_OUT);
   
   CLKOUT2_BUFG_INST : BUFG
      port map (I=>CLKOUT2_BUF,
                O=>CLKOUT2_OUT);
   
   CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLKFB_IN);
   
   DCM_ADV_INST : DCM_ADV
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 10.000,
            CLKOUT_PHASE_SHIFT => "NONE",
            DCM_AUTOCALIBRATION => TRUE,
            DCM_PERFORMANCE_MODE => "MAX_SPEED",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"F0F0",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE,
            SIM_DEVICE => "VIRTEX5")
      port map (CLKFB=>CLKFB_IN,
                CLKIN=>CLKIN_IBUFG,
                DADDR(6 downto 0)=>GND_BUS_7(6 downto 0),
                DCLK=>GND_BIT,
                DEN=>GND_BIT,
                DI(15 downto 0)=>GND_BUS_16(15 downto 0),
                DWE=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>RST_IN,
                CLKDV=>open,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                DO=>open,
                DRDY=>open,
                LOCKED=>DCM_LOCKED_INV_IN,
                PSDONE=>open);
   
   INV_INST : INV
      port map (I=>DCM_LOCKED_INV_IN,
                O=>PLL_LOCKED_INV_RST);
   
   PLL_ADV_INST : PLL_ADV
   generic map( BANDWIDTH => "OPTIMIZED",
            CLKIN1_PERIOD => 10.000,
            CLKIN2_PERIOD => 10.000,
            CLKOUT0_DIVIDE => 20,
            CLKOUT1_DIVIDE => 10,
            CLKOUT2_DIVIDE => 5,
            CLKOUT0_PHASE => 0.000,
            CLKOUT1_PHASE => 0.000,
            CLKOUT2_PHASE => 0.000,
            CLKOUT0_DUTY_CYCLE => 0.500,
            CLKOUT1_DUTY_CYCLE => 0.500,
            CLKOUT2_DUTY_CYCLE => 0.500,
            COMPENSATION => "DCM2PLL",
            DIVCLK_DIVIDE => 1,
            CLKFBOUT_MULT => 8,
            CLKFBOUT_PHASE => 0.0,
            REF_JITTER => 0.000000)
      port map (CLKFBIN=>CLKFBOUT_CLKFBIN,
                CLKINSEL=>VCC_BIT,
                CLKIN1=>CLK0_BUF,
                CLKIN2=>GND_BIT,
                DADDR(4 downto 0)=>DADDR_IN(4 downto 0),
                DCLK=>DCLK_IN,
                DEN=>DEN_IN,
                DI(15 downto 0)=>DI_IN(15 downto 0),
                DWE=>DWE_IN,
                REL=>GND_BIT,
                RST=>PLL_LOCKED_INV_RST,
                CLKFBDCM=>open,
                CLKFBOUT=>CLKFBOUT_CLKFBIN,
                CLKOUTDCM0=>open,
                CLKOUTDCM1=>open,
                CLKOUTDCM2=>open,
                CLKOUTDCM3=>open,
                CLKOUTDCM4=>open,
                CLKOUTDCM5=>open,
                CLKOUT0=>CLKOUT0_BUF,
                CLKOUT1=>CLKOUT1_BUF,
                CLKOUT2=>CLKOUT2_BUF,
                CLKOUT3=>open,
                CLKOUT4=>open,
                CLKOUT5=>open,
                DO=>open,
                DRDY=>DRDY_OUT,
                LOCKED=>LOCKED_OUT);
   
end BEHAVIORAL;


